### ISSUE TITLE
HTTP resource doesnt support accept-ranges: bytes

### ISSUE THREAD

**Issue by todrobbins** [maxogden/mount-url#1]
`HTTP resource doesnt support accept-ranges: bytes`

I'm new to HTTP ranges, what does this error mean? Cheers 🍭

**Comment by max-mapper** [comment]
This means you can only read the file start -> finish, in order, in one shot, as the entire thing. So you can't say 'read byte 573723 of the file until byte 972734' for example. I"ll try and make the help message a little more descriptive

**Comment by max-mapper** [comment]
ok updated the message and added more detail to the readme

**Comment by todrobbins** [comment]
:+1: thanks man!
